# Generated by Django 2.2.3 on 2019-07-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('name_line', models.CharField(blank=True, max_length=50)),
                ('store_id', models.IntegerField(blank=True, default=0)),
                ('line_id', models.CharField(max_length=50)),
            ],
        ),
    ]
