# Generated by Django 2.2.3 on 2019-07-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20190726_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name_line',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='line_id',
            field=models.CharField(max_length=50),
        ),
    ]
