# Generated by Django 2.2.3 on 2019-07-30 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('qty', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('photo_main', models.ImageField(upload_to='product/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='product/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='product/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='product/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='product/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='product/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='product/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
            ],
        ),
    ]
