# Generated by Django 2.2.3 on 2019-07-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo_6',
            field=models.ImageField(upload_to=''),
        ),
    ]
