# Generated by Django 2.2.3 on 2019-07-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190729_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='product/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='product/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='product/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_4',
            field=models.ImageField(blank=True, upload_to='product/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_5',
            field=models.ImageField(blank=True, upload_to='product/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_6',
            field=models.ImageField(blank=True, upload_to='product/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_main',
            field=models.ImageField(upload_to='product/%Y/%m/%d/'),
        ),
    ]
