# Generated by Django 2.2.3 on 2019-08-02 04:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0004_auto_20190730_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('address', models.TextField(blank=True)),
                ('district', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('provice', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=10)),
                ('weight', models.IntegerField()),
                ('increment_id', models.IntegerField()),
                ('subtotal', models.FloatField()),
                ('shipping_method_name', models.CharField(blank=True, max_length=50)),
                ('shipping_amount', models.FloatField()),
                ('payment_method_name', models.CharField(blank=True, max_length=50)),
                ('grand_total', models.FloatField()),
                ('qty', models.IntegerField()),
                ('productName', models.CharField(max_length=50)),
                ('finalPrice', models.FloatField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
